name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Run Jest tests
      run: npm test -- --coverage
    - name: Generate coverage badge
      uses: mattallty/jest-coverage-badges-action@v1.1.0
      with:
        output_file: coverage.svg
    - name: Jest badges generation action
      uses: jpb06/jest-badges-action@v1.9.16
